### ISSUE TITLE
how to get <systemd/sd-bus.h> or install this header file

### ISSUE THREAD

**Issue by liufujun135** [openbmc/ipmitool#2]
hi
build the ipmiotool and then report the following error:
dbus.c:43:28: fatal error: systemd/sd-bus.h: No such file or directory
 #include <systemd/sd-bus.h>

Thanks.

**Comment by jk-ozlabs** [comment]
You'll need recent systemd libraries & headers to get the sd-bus code. How you do this will depend on your distribution.

On Ubuntu (15.10), the package that contains these headers is `libsystemd-dev`.

**Comment by liufujun135** [comment]
My release is Ubuntu 14.04.3 LTS. 
I run "install all libsystemd_" command and It still can not work(systemd/sd-bus.h: No such file or directory).
$sudo apt-get install libsystemd_

Do you have any other idea?

**Comment by jk-ozlabs** [comment]
The version of the systemd headers in 14.04.3 is probably too old; the sd-bus headers were only introduced fairly recently. You could either:
1. Build on 15.10 instead; or
2. Grab a more recent systemd, compile and install it to a non-system path (eg, `--prefix=$HOME/.local`), and use that same prefix when building ipmitool, so it has access to those include directories.

**Comment by liufujun135** [comment]
It is ok after installing libsystemd-dev under 15.10.

Thank you very much.

**Comment by jk-ozlabs** [comment]
Glad you've got it sorted!

**Comment by adanivas** [comment]
How do you install this on a MAC ? 
I tried pip install systemd and get the following errors 
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c systemd/_daemon.c -o build/temp.macosx-10.11-intel-2.7/systemd/_daemon.o
    systemd/_daemon.c:531:10: fatal error: 'systemd/sd-daemon.h' file not found
    #include <systemd/sd-daemon.h>
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-MtZOCt/systemd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jPv2gB-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-MtZOCt/systemd/
